#!/usr/bin/env python3
"""
Generate anomaly explanations using GPT-4o for pipeline outputs.

Reads the sampled frames (originals + heatmap overlays) and anomaly scores
produced by run_pipeline.py, sends them to GPT-4o with a carefully designed
prompt, and saves the generated explanations.

Usage:
    export OPENAI_API_KEY="sk-..."
    python generate_explanations.py --video 01_0162
    python generate_explanations.py --batch
"""

import os
import sys
import json
import base64
import time
import argparse
from pathlib import Path

OUTPUT_BASE = Path(__file__).resolve().parent / "outputs"


def encode_image_b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def make_image_block(path, detail="high"):
    ext = Path(path).suffix.lower()
    media = "image/png" if ext == ".png" else "image/jpeg"
    b64 = encode_image_b64(path)
    return {
        "type": "image_url",
        "image_url": {"url": f"data:{media};base64,{b64}", "detail": detail},
    }


SYSTEM_PROMPT = """\
You are a surveillance video anomaly analyst. You will be shown a set of \
frames sampled from a short segment of a surveillance video that has been \
flagged as anomalous by an automated anomaly detection model.

For each sampled frame you receive TWO images:
1. The original surveillance frame.
2. An anomaly heatmap overlay generated by a reconstruction-based model \
trained exclusively on normal footage from this camera. Warm/bright regions \
indicate areas the model could NOT reconstruct well, meaning they deviate \
from learned normal patterns. Note: the heatmap is approximate and may \
contain noise — use it as a rough guide, not as ground truth.

You also receive the anomaly score for each frame. Normal frames in this \
scene typically score below 0.3; the frames you are shown scored \
significantly higher, indicating statistical deviation.

Your task: Based on ALL the frames, heatmaps, and scores together, provide \
a single concise explanation (1-2 sentences) of what anomalous activity is \
happening in this video segment. Focus on WHAT is unusual and WHY it \
deviates from normal pedestrian behaviour in this scene.

Respond with ONLY a JSON object in this exact format:
{"explanation": "..."}\
"""


def build_user_content(segment_dir, segment_meta, include_heatmap=True):
    """Build the multi-modal user message with all sampled frames."""
    segment_dir = Path(segment_dir)
    frames = segment_meta["sampled_frames"]
    start = segment_meta["start_frame"]
    end = segment_meta["end_frame"]
    duration = segment_meta["duration_frames"]

    score_list = ", ".join(
        f"frame {f['frame_idx']}={f['anomaly_score']:.2f}" for f in frames
    )

    if include_heatmap:
        text = (
            f"This segment spans frames {start}-{end} ({duration} frames) of the video. "
            f"The anomaly detection model flagged this entire interval with elevated scores. "
            f"Per-frame anomaly scores: [{score_list}]. "
            f"Below are the {len(frames)} sampled frames, each followed by its heatmap overlay."
        )
    else:
        text = (
            f"This segment spans frames {start}-{end} ({duration} frames) of the video. "
            f"The anomaly detection model flagged this entire interval with elevated scores. "
            f"Per-frame anomaly scores: [{score_list}]. "
            f"Below are the {len(frames)} sampled frames from this segment."
        )

    content = [{"type": "text", "text": text}]

    for f in frames:
        idx = f["frame_idx"]
        prefix = f"frame_{str(idx).zfill(4)}"

        original_path = segment_dir / f"{prefix}_original.png"
        overlay_path = segment_dir / f"{prefix}_overlay.png"

        if original_path.exists():
            content.append({"type": "text", "text": f"Frame {idx} (score {f['anomaly_score']:.2f}) — original:"})
            content.append(make_image_block(str(original_path)))

        if include_heatmap and overlay_path.exists():
            content.append({"type": "text", "text": f"Frame {idx} — anomaly heatmap overlay (warm = deviation from normal):"})
            content.append(make_image_block(str(overlay_path)))

    return content


def query_gpt4o(system_prompt, user_content):
    from openai import OpenAI
    client = OpenAI()

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
            max_tokens=200,
            response_format={"type": "json_object"},
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"    ERROR: {e}")
        return {"explanation": f"ERROR: {e}"}


def process_video(video_id, include_heatmap=True):
    video_dir = OUTPUT_BASE / video_id

    meta_path = video_dir / "metadata.json"
    if not meta_path.exists():
        print(f"  SKIP {video_id}: no pipeline output found (run run_pipeline.py first)")
        return None

    with open(meta_path) as f:
        meta = json.load(f)

    if meta["num_segments_detected"] == 0:
        print(f"  SKIP {video_id}: no anomaly segments detected")
        return None

    mode_str = "with heatmap" if include_heatmap else "NO heatmap"
    print(f"  {video_id}: {meta['num_segments_detected']} segment(s) [{mode_str}]")

    results = {
        "video_id": video_id,
        "total_frames": meta["total_frames"],
        "segments": [],
    }

    for seg in meta["segments"]:
        seg_idx = seg["segment_index"]
        seg_dir = video_dir / f"segment_{seg_idx}"
        seg_meta_path = seg_dir / "metadata.json"

        if not seg_meta_path.exists():
            continue

        with open(seg_meta_path) as f:
            seg_meta = json.load(f)

        print(f"    Segment {seg_idx} (frames {seg_meta['start_frame']}-{seg_meta['end_frame']}) ...", end=" ", flush=True)

        user_content = build_user_content(seg_dir, seg_meta, include_heatmap=include_heatmap)
        response = query_gpt4o(SYSTEM_PROMPT, user_content)

        explanation = response.get("explanation", "")
        print(f"-> \"{explanation[:80]}{'...' if len(explanation) > 80 else ''}\"")

        seg_result = {
            "segment_index": seg_idx,
            "start_frame": seg_meta["start_frame"],
            "end_frame": seg_meta["end_frame"],
            "include_heatmap": include_heatmap,
            "explanation": explanation,
        }
        results["segments"].append(seg_result)

        suffix = "" if include_heatmap else "_no_heatmap"
        with open(seg_dir / f"explanation{suffix}.json", "w") as f:
            json.dump(seg_result, f, indent=2)

        time.sleep(0.5)

    suffix = "" if include_heatmap else "_no_heatmap"
    with open(video_dir / f"explanations{suffix}.json", "w") as f:
        json.dump(results, f, indent=2)

    return results


def main():
    parser = argparse.ArgumentParser(description="Generate anomaly explanations via GPT-4o")
    parser.add_argument("--video", type=str, help="Single video ID, e.g. 01_0162")
    parser.add_argument("--batch", action="store_true", help="Process all videos in outputs/")
    parser.add_argument("--no-heatmap", action="store_true", help="Send only original frames, no heatmap overlays")
    args = parser.parse_args()

    if not args.video and not args.batch:
        parser.error("Specify --video VIDEO_ID or --batch")

    if not os.environ.get("OPENAI_API_KEY"):
        print("ERROR: Set OPENAI_API_KEY environment variable first.")
        sys.exit(1)

    include_heatmap = not args.no_heatmap

    if args.batch:
        video_dirs = sorted([
            d.name for d in OUTPUT_BASE.iterdir()
            if d.is_dir() and (d / "metadata.json").exists()
        ])
        print(f"Batch mode: {len(video_dirs)} video(s) with pipeline outputs\n")

        all_results = []
        for i, vid in enumerate(video_dirs):
            print(f"[{i+1}/{len(video_dirs)}]", end=" ")
            result = process_video(vid, include_heatmap=include_heatmap)
            if result:
                all_results.append(result)

        suffix = "" if include_heatmap else "_no_heatmap"
        summary_path = OUTPUT_BASE / f"explanations_summary{suffix}.json"
        with open(str(summary_path), "w") as f:
            json.dump(all_results, f, indent=2)
        print(f"\nDone. Summary saved to: {summary_path}")
    else:
        result = process_video(args.video, include_heatmap=include_heatmap)
        if result:
            suffix = "" if include_heatmap else "_no_heatmap"
            print(f"\nDone. Result saved to: {OUTPUT_BASE / args.video / f'explanations{suffix}.json'}")


if __name__ == "__main__":
    main()
